version: "3"
services:
  app:
    build: .
    volumes:
      - .:/Facebook_scrapper
    ports:
      - 8000:8000
    depends_on:
      - mongo
  mongo:
    image: mongo
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: haythem
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27017:27017 # remove this line on prod